### ISSUE TITLE
ament_black is broke with the latest versions of Black

### ISSUE THREAD

**Issue by gstorer** [botsandus/ament_black#12] opened 2024-04-05 05:48 UTC
The API to get_sources has changed recently and an exception is thrown when running ament_black with newer versions of Black:
```
      - /opt/ros/humble/install/ament_black/bin/ament_black
     Traceback (most recent call last):
       File "/opt/ros/humble/install/ament_black/bin/ament_black", line 33, in <module>
         sys.exit(load_entry_point('ament-black==0.2.4', 'console_scripts', 'ament_black')())
       File "/opt/ros/humble/install/ament_black/lib/python3.8/site-packages/ament_black/main.py", line 81, in main
         sources = get_sources(
     TypeError: get_sources() missing required keyword-only argument 'root'
```
API change:
https://github.com/psf/black/pull/3847

I think this line https://github.com/botsandus/ament_black/blob/main/ament_black/ament_black/main.py#L82 needs to change to something like this to support new versions:
`root=click.Context(black).obj["root"],`

I guess you may want to add a version check or inspect the function signature to continue to support old versions as well.

**Comment by nachovizzo** [comment] 2024-04-08 09:31
Thanks for reporting this @gstorer . It's a well-known issue and a duplicate of https://github.com/botsandus/ament_black/issues/10

Sadly I don't have control in the horrible way python packages are baked in ROS, which for example completely ignores version dependencies that have been solved in python since decades
https://github.com/botsandus/ament_black/blob/0790620546a713431f4875a274cf20368fa26235/ament_black/setup.py#L15

What happens here is that you are using a "not officially" supported black version. ROS packages are meant to work with the system packages, in the case of the current LTS release of ubuntu 22.04, that is ` sudo apt install black` which is the version that I tried to specify in the setup.py and is completely ignored in the ROS ecosystem

**Closed as completed by nachovizzo** 2024-04-08 09:31 UTC

**Comment by gstorer** [comment] 2024-04-15 03:19
@nachovizzo 
Shouldn't we fix this? ROS2 Jazzy is due out in a few weeks and Ubuntu Noble's default Black version is 24.2 which won't work with this package. I can throw together a pull request if you want...

**Comment by nachovizzo** [comment] 2024-04-22 14:39
@gstorer sorry for the delay
 
PRs more than welcome. I think the right solution would be to provide a new release for jammy, so it is clear this needs to be fixed. Want to draft a PR? I can take over the release madness, that takes 55 steps I have noted down somewhere
